CompileFlags:
  Add:
    # - -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1
    # - -I/usr/local/Cellar/gcc/15.1.0/include/c++/15
    # - -I/usr/local/Cellar/gcc/15.1.0/include/c++/15/x86_64-apple-darwin23/
    - -I/usr/local/Cellar/gcc/15.1.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin23/15/../../../../../../include/c++/15
    - -I/usr/local/Cellar/gcc/15.1.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin23/15/../../../../../../include/c++/15/x86_64-apple-darwin23
    - -I/usr/local/Cellar/gcc/15.1.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin23/15/../../../../../../include/c++/15/backward
    - -I/usr/local/Cellar/gcc/15.1.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin23/15/include
    - -I/usr/local/Cellar/gcc/15.1.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin23/15/include-fixed
    - -I/Library/Developer/CommandLineTools/SDKs/MacOSX26.sdk/usr/include
    - -I/Library/Developer/CommandLineTools/SDKs/MacOSX26.sdk/System/Library/Frameworks
    - -std=c++20

Diagnostics:
  UnusedIncludes: None
